// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the token.properties.

// Token header for the Scenes Server Cluster plugin.

// Token header for the Manufacturing Library CLI plugin.

// Token header for the Reporting plugin.

// Custom MFG token header file
#include "my_mfgtoken.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

